### ISSUE TITLE
Continous Integration on Python nightly (3.10): re does not match for 2 exceptions because of qualified names ("my_class.my_method")

### ISSUE THREAD

**Issue by SylvainDe** [SylvainDe/DidYouMean-Python#47]
**First failure**

Date: 27th May 2020
Build: https://travis-ci.org/github/SylvainDe/DidYouMean-Python/builds/691583710
Jobs: https://travis-ci.org/github/SylvainDe/DidYouMean-Python/jobs/691583732

```
$ python -VV
Python 3.10.0a0 (heads/master:5eb45d7, May 26 2020, 13:13:09) 
[GCC 5.4.0 20160609]
$ python -c "import sys; print(sys._git)" || true
('CPython', 'heads/master', '5eb45d7')
```

```
AssertionError: Regex didn't match: "^(?P<func><?\\w+>?)\\(\\) got an unexpected keyword argument '(?P<arg>[^\\d\\W]\\w*)'$" not found in "MyClass.func() got an unexpected keyword argument 'babar'" : Running following code :
...
AssertionError: Regex didn't match: "^(?P<func><?\\w+>?)(?:\\(\\) takes| expected) (?:exactly |at least |at most |from )?(?P<expected>no|\\d+|\\d+ to \\d+) (?:positional |non-keyword )?arguments?,? \\(?(?:but |got )?(?P<actual>\\d+)(?: were given| was given| given)?\\)?(?:\\. Did you forget 'self' in the function definition\\?)?$" not found in 'FoobarClass.some_cls_method_missing_cls() takes 0 positional arguments but 1 was given'
...
Ran 368 tests in 1.500s

FAILED (failures=9)
...

```

**Last success**

Date: 26th May 2020
Build: https://travis-ci.org/github/SylvainDe/DidYouMean-Python/builds/691161784
Jobs: https://travis-ci.org/github/SylvainDe/DidYouMean-Python/jobs/691161806

```
$ python -VV
Python 3.9.0b1+ (heads/3.9:82c274e, May 25 2020, 04:36:39) 
[GCC 5.4.0 20160609]
$ python -c "import sys; print(sys._git)" || true
('CPython', 'heads/3.9', '82c274e')
```

**Comment by SylvainDe** [comment]
**Changelog**

```
$ git log 82c274e..5eb45d7 --oneline
5eb45d7d4e bpo-40737: Fix possible reference leak for sqlite3 initialization (GH-20323)
be63019ed7 bpo-40637: Fix test_pbkdf2_hmac_py for missing sha1 (#20422)
af7553ac95 bpo-39301: State that floor division is used for right shift operations (GH-20347)
1c5d1d7304 Remove duplicated words words (GH-20413)
2b0e654f91 bpo-40745: Fix typos in NewType docs (GH-20379)
3cfe5b7b8f Simplify creation of the __new__ method in namedtuple() (GH-20361)
a2bbedc8b1 Fix peg_generator compiler warnings under MSVC (GH-20405)
4a0ac42c52 closes bpo-40774: Fix docs indentation for asyncio.create_subprocess_shell() (GH-20403)
f7b1e46156 bpo-38964: Print correct filename on a SyntaxError in an fstring (GH-20399)
2602d97a0a [workflow] Use Sphinx problem matcher on GitHub docs builds (GH-20325)
9645930b5b bpo-40688: Use the correct parser in the peg_generator scripts (GH-20235)
448325369f bpo-23082: Better error message for PurePath.relative_to() from pathlib (GH-19611)
2377a9bae3 Closes bpo-40558: update CONTRIBUTING.rst to reflect current branches (GH-19989)
deb4355a37 bpo-40750: Do not expand the new parser debug flags if Py_BUILD_CORE is not defined (GH-20393)
800a35c623 bpo-40750: Support -d flag in the new parser (GH-20340)
7d847e29d7 bpo-39573: Fix buildbot failure for tupleobject.c (GH-20391)
ad3252bad9 bpo-39573: Convert Py_TYPE() to a static inline function (GH-20290)
e50883ccc4 bpo-39245: Fix docs links to the stable ABI (GH-20388)
e682b26a6b bpo-34397: Remove redundant overflow checks in list and tuple implementation. (GH-8757)
ef16958d17 bpo-38972: Fix typos in PowerShell Execution Policies links (GH-20383)
20c22db602 bpo-40671: Prepare _hashlib for PEP 489 (GH-20180)
4cc2f9348c bpo-40695: Limit hashlib builtin hash fallback (GH-20259)
3f59b55316 bpo-35714: Reject null characters in struct format strings (GH-16928)
372ee27d49 bpo-38580: Document that select() accepts iterables, not just sequences (GH-16832)
cba5031510 bpo-40334: Support suppressing of multiple optional variables in Pegen (GH-20367)
c73914a562 bpo-36290: Fix keytword collision handling in AST node constructors (GH-12382)
59f5022b5d bpo-17050: Remove documentation on argparse.REMAINDER (GH-18661)
3436f5f899 bpo-40443: Remove unused imports in the zoneinfo (GH-20354)
16ef324193 bpo-37309: Update IDLE NEWS.txt (GH-20356)
905b3cd05f bpo-40723: Make IDLE autocomplete test run without __main__.__file__ (GH-20311)
fdc5a94279 bpo-37973: Improve the docstrings of sys.float_info (GH-19218)
3f5f61409e Remove spurious NULL in descrobject.c (GH-20344)
b23d7adfdf Use Py_ssize_t for the column number in the PEG support code (GH-20341)
13206b52d1 bpo-40405: Fix asyncio.as_completed docs (GH-19753)
1cba1c9aba bpo-34556: Document addition of upgrade_deps to venv.create (GH-20135)
af23f0d3cf bpo-40439: Update broken link in lexical analysis docs (GH-20184)
8022eb4e97 [doc] Add missing space in urllib.request.rst (GH-19860)
da51ba442c Cosmetic smtplib changes (GH-8718)
6fad3e6b49 bpo-40552 Add 'users' variable in code sample (tutorial 4.2). (GH-19992)
b5cc2089cc bpo-40679: Use the function's qualname in certain TypeErrors (GH-20236)
7c30d12bd5 bpo-40696: Fix a hang that can arise after gen.throw() (GH-20287)
909b5714e1 bpo-9216: hashlib usedforsecurity fixes (GH-20258)
06a1b8915d bpo-40705: Fix use-after-free in _zoneinfo's module_free (GH-20280)
30d5a7364d bpo-40730: Remove redundant 'to' (GH-20316)
0226f3eba0 Let the argument clinic do the type checking for heapq (GH-20284)
8b62644831 bpo-40630: Add tracemalloc.reset_peak (GH-20102)
bfaf5275ad Restore missing column of digits (GH-20313)
b831129123 Fix debug output in PEG parser generator (GH-20308)
ae14583302 bpo-40334: Produce better error messages for non-parenthesized genexps (GH-20153)
7864f11cdf [doc] Remove references to obsolete BuildApplet on macOS. (GH-20023)
b8a65ec1d3 bpo-40715: Reject dict unpacking on dict comprehensions (GH-20292)
72e0aa2fd2 bpo-40176: Improve error messages for trailing comma on from import (GH-20294)
d10fef35c6 Fix typing problems reported by mypy in pegen (GH-20297)
2e76820a50 Reword aware/naive introduction sentence (GH-20175)
f50516e6a9 bpo-40334: Correctly generate C parser when assigned var is None (GH-20296)
a487a39dca bpo-40714: Remove compile warning from _zoneinfo.c (GH-20291)
e16d2f7c37 Improve output summary in the examples and recipes section (GH-20285)
0f56263e62 bpo-32309: Add support for contextvars in asyncio.to_thread() (GH-20278)
7efb826c3e Use f-strings in argparse HOWTO (GH-20070)
df2e0ff0d6 Update whatsnew benchmark results for 3.9 (GH-20276)
f2947e354c s/wakup/wakeup (GH-20250)
7fbe65dbc4 Use v2 of GitHub Actions where available (GH-20232)
e572c7f6db bpo-40698: Improve distutils upload hash digests (GH-20260)
bac170cd93 bpo-34956: edit and format better NEWS item in 3.9.0b1 changelog (GH-20255)
da7d1f0408 Fix the URL to fishshell.com (GH-20251)
550f30c8f3 bpo-40291: Mention socket.CAN_J1939 in What's New (GH-20248)
0509c4547f bpo-40521: Fix update_slot() when INTERN_NAME_STRINGS is not defined (#20246)
aca4670ad6 bpo-40645: restrict HMAC key len to INT_MAX (GH-20238)
dd74b6fde3 bpo-38870: invalid escape sequence (GH-20240)
92327a9913 bpo-39631: Adds NEWS entry (GH-20227)
9d17cbf33d bpo-32604: PEP 554 for use in test suite (GH-19985)
c105f7d895 Enable GitHub Actions for 3.9 branch (GH-20231)
2a561b5f68 bpo-37616: Handle version information more gracefully in getpath.c (GH-20214)
2abededbc4 bpo-40683: Add zoneinfo to LIBSUBDIRS (#20229)
a355a06fcc Fix typo in multiprocessing documentation (GH-20016)
19e3e00264 Doc: Python 3.10 in sidebar and version switcher. (GH-20209)
711f9e180a bpo-40677: Define IO_REPARSE_TAG_APPEXECLINK explicitly (GH-20206)
8c862e5124 bpo-39631: Fix file association MIME type in the Windows installer (GH-20205)
29251b787b 3.10 whatsnew needs to use blurb-produced changelog (GH-20213)
18cb3be41b Consolidate 3.9.0b1 NEWS in the master branch
cc2bbc2227 bpo-32309: Implement asyncio.to_thread() (GH-20143)
d4fe098d1e Python 3.10.0a0 (GH-20198)
9095f76613 Fix code-block in zoneinfo (GH-20201)
3764069f3b bpo-40669: Use requirements.pip when installing PEG dependencies (GH-20194)
ff7a8b03c4 Use _PyErr_ChainStackItem() inside gen_send_ex(). (GH-20173)
```

**Comment by SylvainDe** [comment]
**First error: unexpected keyword argument**

> AssertionError: Regex didn't match: "^(?P<func><?\\w+>?)\\(\\) got an unexpected keyword argument '(?P<arg>[^\\d\\W]\\w*)'$" not found in "MyClass.func() got an unexpected keyword argument 'babar'" : Running following code :

is probably caused by https://github.com/python/cpython/commit/b5cc2089cc354469f12eabc7ba54280e85fdd6dc


**Second error: func takes n positional argument**

> AssertionError: Regex didn't match: "^(?P<func><?\\w+>?)(?:\\(\\) takes| expected) (?:exactly |at least |at most |from )?(?P<expected>no|\\d+|\\d+ to \\d+) (?:positional |non-keyword )?arguments?,? \\(?(?:but |got )?(?P<actual>\\d+)(?: were given| was given| given)?\\)?(?:\\. Did you forget 'self' in the function definition\\?)?$" not found in 'FoobarClass.some_cls_method_missing_cls() takes 0 positional arguments but 1 was given'

is probably caused by the same commit.


**Analysis**

It looks like we should expect qualified names to be used now. This looks similar to https://github.com/SylvainDe/DidYouMean-Python/issues/44 .

**Comment by SylvainDe** [comment]
Everything seems to be fixed now: https://travis-ci.org/github/SylvainDe/DidYouMean-Python/builds/691629028
